
version: "3.9"
services:
  freteapi:
    build:
      context: ./frete-api
    image: freteapi:latest
    container_name: freteapi
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - API_PORT=8080
      - ERP_SQL_CONN=${ERP_SQL_CONN}
      - FRETE_SQL_CONN=${FRETE_SQL_CONN}
    ports:
      - "8800:8080"
