
version: "3.9"
services:
  freteapi:
    build:
      context: ./frete-api
    image: freteapi:latest
    container_name: freteapi
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
      - API_PORT=8080
    ports:
      - "8800:8080"
